mesd_app:
    resource: "@MesdAppBundle/Resources/config/routing.yml"
    prefix:   /

MesdUserBundle_security:
    resource: "@MesdUserBundle/Resources/config/routing/security.yml"

MesdUserBundle_registration:
    resource: "@MesdUserBundle/Resources/config/routing/registration.yml"
    prefix: /register

MesdUserBundle_reset:
    resource: "@MesdUserBundle/Resources/config/routing/reset.yml"
    prefix: /reset

MesdAppBundle_user:
    resource: "@MesdAppBundle/Resources/config/routing/user.yml"
    prefix:   /user
