security:
    encoders:
        Mesd\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        mesd_user:
            id: mesd_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|ico)/
            security: false

        login:
            context:    default_context
            pattern:    ^/(login$|registration|reset)
            anonymous:  true

        main:
            context:    default_context
            pattern:    ^/
            form_login:
                csrf_provider:       form.csrf_provider
                login_path:          MesdUserBundle_login
                check_path:          MesdUserBundle_check
                default_target_path: _welcome
            logout:
                path:   MesdUserBundle_logout
                target: MesdUserBundle_login

    #access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }